[package]
name = "cega"
description = "CGA and EGA binary image file processing library"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knzconnor/cega"

[features]
#default = ["termart", "sdl2"]
#termart = ["clap-v3"]

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]
bitvec = "1"
# strum = "0.26"
# strum_macros = "0.26"
#including for credit, but had to rework code to be a lib
#rascii = { version = "0.1.2", optional = true } 

clap = { version = "4.5.7", features = ["derive"] }
#image = { version = "0.21.2", optional = true }
#termcolor = { version = "1", optional = true } 

[dependencies.sdl2]
version = "0.37.0"
#optional = true
default-features = false
features = ["gfx"]
