[package]
name = "cega"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1"

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies.sdl2]
version = "0.37.0"
optional = true
default-features = false
features = ["gfx"]