[package]
name = "cega"
description = "CGA and EGA binary image file processing library"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knzconnor/cega"
readme = "README.md"
keywords = ["gamedev", "graphics"]
categories = ["command-line-utilities"]
exclude = [".rusty-hook.toml", ".gitignore"]

[features]
default = ["terminal"]
terminal = ["clap", "sdl2"]

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]
bitvec = "1"
factor = "0.4.0"

clap = { version = "4.5.7", features = ["derive"], optional = true }

[dependencies.sdl2]
version = "0.37.0"
optional = true
default-features = false
features = ["gfx"]
